### ISSUE TITLE
HomeAssistant

### ISSUE THREAD

**Issue by sdavides** [leicaflorian/tvit#2]
Ho creato un flusso nodered per homeassistant del tuo progetto, può interessarti?
Se vuoi magari citarmi nella pagina principale.ciao

https://github.com/sdavides/EPGItaly-Homeassistant

**Comment by leicaflorian** [comment]
Mi dispiace non averti risposto prima. Purtroppo non ho avuto molto tempo da dedicarci. Cmq HomeAssistant non lo conosco, però sarebbe interessante collegare le due applicazionie.
