### ISSUE TITLE
Lista canali ed epg non funzionanti

### ISSUE THREAD

**Issue by andreabellitto** [leicaflorian/tvit#3]
Ciao, uso le liste su android tramite l'app Tivimate, le liste

- https://tvit.leicaflorianrobert.dev/iptv/list.m3u
- https://tvit.leicaflorianrobert.dev/epg/list.xml

hanno sempre funzionato correttamente, da qualche giorno invece non si vedono più né i canali (nessuno), ne la guida epg.

A schermo da errore:

**HttpDataSource$HttpDataSourceException**

Ho provato da più dispositivi.

**Comment by leicaflorian** [comment]
Ciao @andreabellitto ,
mi fa piacere sapere che usi la mia lista e mi dispiace per il problema riscontrato.

Cmq dovrei aver sistemato. Ho cambiato qualche giorno fa il server e c'era un problema di configurazione.

Se riscontri ancora problemi, nn esitare a farmelo sapere.
