### ISSUE TITLE
Non funziona più

### ISSUE THREAD

**Issue by sdavides** [leicaflorian/tvit#4]
Non funziona più, il json è vuoto

**Comment by leicaflorian** [comment]
Ciao @sdavides , mi dispiace per l'inconveniente. C'era un errore nello schedulare il cron quotidiano che generava il json. Ora dovrebbe essere a posto. Questo viene generato ogni notte alle 03:00 ora italiana.

**Comment by sdavides** [comment]
Cazzarola, avevo creato un addon per home assistant con nodered, ho visto che non rispondevi, l'ho cancellato senza fare il backup.
Posso chiederti dove prendi la sorgente per creare il json?

**Comment by leicaflorian** [comment]
Ah cavolo, mi dispiace. Cmq il json lo genero facendo lo scrapping da https://www.superguidatv.it
Nel progetti trovi il codice dentro app/Jobs/Scrappers/SuperGuidaTvScrapper.php

**Comment by sdavides** [comment]
Lo scrapping sulla codice html?
Non c'è un link api che mi risponde con il json ?

Io ho dei link api da https://services.tivulaguida.it/api/
ma non ha le immagini e per alcuni canali non è preciso

**Comment by leicaflorian** [comment]
Eh si, scarpping html.
Avevo cercato ma non ho trovato alcun json. Uso superGuidaTv perchè contiene appunto le immagini e di solito la guida è affidabile. Purtroppo al momento non trovo una soluzione migliore.,

**Comment by sdavides** [comment]
ok grazie mille

**Comment by leicaflorian** [comment]
grazie a te. Cmq ora il mio json dovrebbe funzionare correttamente senza più intoppi. Tutto è successo perchè avevo cambiato hosting e nel nuovo avevo inserito una configurazione che bloccava i cron. Ora questo è risolto e non ho intenzione di cambiare più hosting.
