### ISSUE TITLE
Non funziona di nuovo

### ISSUE THREAD

**Issue by sdavides** [leicaflorian/tvit#6]
Non funziona di nuovo, il json è vuoto

**Comment by leicaflorian** [comment]
Ciao, ora vedo che funziona tutto. Ho controllato i log ma non ci sono problemi, quindi deduco che sia un problema del sito da cui faccio lo scrapping. Eventualmente in futuro proverò a cercare qualche altro sito da sfruttare.

**Comment by sdavides** [comment]
Capisci bene che non è affidabile lo scrapping.

questo è il link api del sito dove fai scraping già in json:

https://api-ng.superguidatv.it/v3/channels-events?bouquetId=3&startDate=2024-07-05T00%3A00%3A00&timeFrame=now&orderBy=channelNumber&ct-ver=1is&bld=504117&plt=ANDROID

(cambia la data)

**Comment by leicaflorian** [comment]
Ah, wow, grazie per il json, grazie mille! Appena ho un attimo vedo di integrarlo.

 <https://mysig.io/OWVlZTE>	
Florian Robert Leica   
m:  +39 3202942127 <tel:+39 3202942127>
w:  leicaflorianrobert.dev <https://mysig.io/ZDRlNTE>
e:  ***@***.*** ***@***.***>
