### ISSUE TITLE
Canali discovery e sky sono giù

### ISSUE THREAD

**Issue by xunil89** [leicaflorian/tvit#7]
https://github.com/Tundrak/IPTV-Italia/raw/main/iptvita.m3u
#EXTINF:-1,[52] DMAX
https://amg16146-wbdi-amg16146c8-samsung-it-1841.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-dmax-samsungit/playlist.m3u8
#EXTINF:-1,[31] Real Time
https://amg16146-wbdi-amg16146c2-samsung-it-1835.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-realtime-samsungit/playlist.m3u8
#EXTINF:-1,[8] TV8
https://hlslive-web-gcdn-skycdn-it.akamaized.net/TACT/11223/tv8web/master.m3u8?hdnea=st=1701861650~exp=1765449000~acl=/*~hmac=84c9f3f71e57b13c3a67afa8b29a8591ea9ed84bf786524399545d94be1ec04d
#EXTINF:-1,[9] NOVE
https://amg16146-wbdi-amg16146c1-samsung-it-1831.playouts.now.amagi.tv/playlist/amg16146-warnerbrosdiscoveryitalia-nove-samsungit/playlist.m3u8
#EXTINF:-1,[26] Cielo
https://hlslive-web-gcdn-skycdn-it.akamaized.net/TACT/11219/cieloweb/master.m3u8?hdnea=st=1701861650~exp=1765449000~acl=/*~hmac=84c9f3f71e57b13c3a67afa8b29a8591ea9ed84bf786524399545d94be1ec04d

Questi sono funzionanti 

Sarebbe comodo mettere la lista su ghitub per permettere la modifica a tutti cosi da avere canali aggiornati più rapidamente

**Comment by leicaflorian** [comment]
Ciao @xunil89 , grazie mille per la tua lista e per i canali indicati. Ho aggiornato l'app e per ora funzionano bene.

Per quanto riguarda la lista, purtroppo non ho modo di farlo in quanto la maggior parte dei canali sono frutto di reverse engineering fatto sui rispettivi siti web delle aziende. Ho estrappolato il modo in cui questi facevano funzionare i loro canali in streaming ed ho emulato il loro meccanismo. Questo significa gestire blocchi CORRS, geo blocking e molto altro.

Se qualcuno ha qualche suggerimento o vuole contribuire al progetto, o come te vuole suggerire dei nuovi link, fatelo pure e appena potrò li aggiornerò. 

Grazie ancora per il tuo prezioso contributo.
